# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 40))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setGeometry(QtCore.QRect(272, 170, 200, 196))
        self.menufile.setObjectName("menufile")
        self.menufunction = QtWidgets.QMenu(self.menubar)
        self.menufunction.setGeometry(QtCore.QRect(318, 170, 200, 158))
        self.menufunction.setObjectName("menufunction")
        self.menudata = QtWidgets.QMenu(self.menubar)
        self.menudata.setGeometry(QtCore.QRect(362, 153, 200, 141))
        self.menudata.setObjectName("menudata")
        self.menuabout_us = QtWidgets.QMenu(self.menubar)
        self.menuabout_us.setGeometry(QtCore.QRect(408, 153, 200, 111))
        self.menuabout_us.setObjectName("menuabout_us")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.actionperpage = QtWidgets.QAction(MainWindow)
        self.actionperpage.setObjectName("actionperpage")
        self.actionperpage.setEnabled(False)
        self.actionprint = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images\print2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprint.setIcon(icon)
        self.actionprint.setObjectName("actionprint")
        self.actionprint.setEnabled(False)
        self.actionchangepassword = QtWidgets.QAction(MainWindow)
        self.actionchangepassword.setObjectName("actionchangepassword")
        self.actionquit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images\quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionquit.setIcon(icon1)
        self.actionquit.setObjectName("actionquit")
        self.actionmeeting = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images\meeting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmeeting.setIcon(icon2)
        self.actionmeeting.setObjectName("actionmeeting")
        self.actionmeeting.setEnabled(False)
        self.actionmeeting.setCheckable(True)
        self.actioninvest = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images\invest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioninvest.setIcon(icon3)
        self.actioninvest.setObjectName("actioninvest")
        self.actioninvest.setEnabled(False)
        self.actioninvest.setCheckable(True)
        self.actioninstruct = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images\instruct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioninstruct.setIcon(icon4)
        self.actioninstruct.setObjectName("actioninstruct")
        self.actioninstruct.setEnabled(False)
        self.actioninstruct.setCheckable(True)
        self.actioninspect = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images\inspect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioninspect.setIcon(icon5)
        self.actioninspect.setObjectName("actioninspect")
        self.actioninspect.setEnabled(False)
        self.actioninspect.setCheckable(True)
        self.actioninput = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images\input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioninput.setIcon(icon6)
        self.actioninput.setObjectName("actioninput")
        self.actioninput.setEnabled(False)
        self.actionoutput = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images\output.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionoutput.setIcon(icon7)
        self.actionoutput.setObjectName("actionoutput")
        self.actionoutput.setEnabled(False)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionhelp.setEnabled(True)
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.menufile.addAction(self.actionperpage)
        self.menufile.addAction(self.actionprint)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionchangepassword)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionquit)
        self.menufunction.addAction(self.actionmeeting)
        self.menufunction.addAction(self.actioninvest)
        self.menufunction.addAction(self.actioninstruct)
        self.menufunction.addAction(self.actioninspect)
        self.menudata.addAction(self.actioninput)
        self.menudata.addAction(self.actionoutput)
        self.menudata.addSeparator()
        #self.menudata.addAction(self.actionData_Analytical)
        self.menuabout_us.addAction(self.actionhelp)
        self.menuabout_us.addSeparator()
        self.menuabout_us.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menufunction.menuAction())
        self.menubar.addAction(self.menuabout_us.menuAction())
        self.toolBar.addAction(self.actionmeeting)
        self.toolBar.addAction(self.actioninvest)
        self.toolBar.addAction(self.actioninstruct)
        self.toolBar.addAction(self.actioninspect)
        self.toolBar_2.addAction(self.actioninput)
        self.toolBar_2.addAction(self.actionoutput)
        self.toolBar_3.addAction(self.actionprint)
        self.toolBar_3.addAction(self.actionquit)

        self.retranslateUi(MainWindow)
        self.actionquit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Audit information statistics platform"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menufunction.setTitle(_translate("MainWindow", "Features"))
        self.menudata.setTitle(_translate("MainWindow", "Data"))
        self.menuabout_us.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.actionperpage.setText(_translate("MainWindow", "Page Settings"))
        self.actionprint.setText(_translate("MainWindow", "Print"))
        self.actionprint.setToolTip(_translate("MainWindow", "Print form content"))
        self.actionprint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        #self.actionregist.setText(_translate("MainWindow", "xxx"))
        self.actionchangepassword.setText(_translate("MainWindow", "Change Password"))
        #self.actionlogin.setText(_translate("MainWindow", "xx"))
        self.actionquit.setText(_translate("MainWindow", "Log Out"))
        self.actionquit.setToolTip(_translate("MainWindow", "Click to log out"))
        self.actionquit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionmeeting.setText(_translate("MainWindow", "Meeting"))
        self.actionmeeting.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actioninvest.setText(_translate("MainWindow", "Audit Investigation Record"))
        self.actioninvest.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actioninstruct.setText(_translate("MainWindow", "Rectification opinions"))
        self.actioninstruct.setShortcut(_translate("MainWindow", "Alt+I"))
        self.actioninspect.setText(_translate("MainWindow", "Rectification inspection"))
        self.actioninspect.setShortcut(_translate("MainWindow", "Alt+J"))
        self.actioninput.setText(_translate("MainWindow", "Import"))
        self.actionoutput.setText(_translate("MainWindow", "Export"))
        #self.actionData_Analytical.setText(_translate("MainWindow", "xxx"))
        #self.actionData_Analytical.setShortcut(_translate("MainWindow", "Alt+A"))
        self.actionhelp.setText(_translate("MainWindow", "Help"))
        self.actionhelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About"))

